### ISSUE TITLE
reject feature

### ISSUE THREAD

**Issue by benjohnsonnlp** [CMSC-201/office-hours-bot#15]
allow TAs to simply answer a queue item instead of opening a session

**Comment by mneary1** [comment]
what is the preferred way to handle this? via DM? what if the student asks something whose answer should be made known to the whole class?

**Comment by minxch** [comment]
I figure that we can have two "quick answers";
one to directly answer
one to tag everyone in maybe a designated channel, like #announcements ?

**Comment by benjohnsonnlp** [comment]
I think that it should be a DM to the student in question with an answer to their queue question.

**Comment by minxch** [comment]
Actually, yeah, if anything were announcement worthy, I think we could probably make that discretion ourselves, and quick answers can go to their DMs directly

**Comment by minxch** [comment]
#29
